WebMvc/Controllers/CatalogController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebMvc.Services;
using WebMvc.ViewModels;

namespace WebMvc.Controllers
{
    public class CatalogController : Controller
    {
        private readonly ICatalogService _service;
        public CatalogController(ICatalogService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Index(int? page, int? brandFilterApplied, int? typesFilterApplied)
        {
            var itemsOnPage = 10;

            var catalog = await _service.GetCatalogItemsAsync(page ?? 0, itemsOnPage, brandFilterApplied, typesFilterApplied);

            var vm = new CatalogIndexViewModel
            {
                CatalogItems = catalog.Data,
                Brands = await _service.GetBrandsAsync(),
                Types = await _service.GetTypesAync(),
                PaginationInfo = new PaginationInfo
                {
                    ActualPage = page ?? 0,
                    ItemsPerPage = catalog.Data.Count,
                    TotalItems = catalog.Count,
                    TotalPages = (int)Math.Ceiling((decimal)catalog.Count/itemsOnPage)

                },
                BrandFilterApplied = brandFilterApplied ?? 0,
                TypesFilterApplied = typesFilterApplied ?? 0
            };

            return View(vm);
        }

        [Authorize]
        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";


            return View();
        }
    }
}

WebMvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebMvc</title>

    <environment names="Development,Staging,Production">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/app.css" />
        <link rel="stylesheet" href="~/css/app.component.css" />
        <link rel="stylesheet" href="~/css/shared/components/header/header.css" />
        <link rel="stylesheet" href="~/css/shared/components/identity/identity.css" />
        <link rel="stylesheet" href="~/css/shared/components/pager/pager.css" />
        <link rel="stylesheet" href="~/css/basket/basket.component.css" />

        <link rel="stylesheet" href="~/css/basket/basket-status/basket-status.component.css" />
        <link rel="stylesheet" href="~/css/catalog/catalog.component.css" />

        <link rel="stylesheet" href="~/css/override.css" type="text/css" />
        @*<link rel="stylesheet" href="~/css/sitestripe.css" type="text/css" />*@


    </environment>
    @*<environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>*@
</head>
<body>
    <header class="navbar navbar-light navbar-static-top">
        <div class="container">
            <article class="row">
                <section class="col-lg-7 col-md-6 col-xs-12">
                    <a class="navbar-brand" routerLink="catalog">
                        <a asp-area="" asp-controller="Catalog" asp-action="Index">
                            <img src="~/images/logo-4.png" />
                        </a>
                    </a>
                </section>
               @*@await Html.PartialAsync("_LoginPartial")*@
            </article>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    
                    <li><a asp-area="" asp-controller="Catalog" asp-action="About">About</a></li>
                   
                </ul>
                
            </div>
        </div>
    </header>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer class="esh-app-footer">
            <div class="container">
                <article class="row">

                    <section class="col-sm-6">
                        <img class="esh-app-footer-brand" src="~/images/logo-4.png" />
                    </section>

                    <section class="col-sm-6">
                        <img class="esh-app-footer-text hidden-xs" src="~/images/main_footer_text.png" width="335" height="26" alt="footer text image" />
                    </section>

                </article>
            </div>
        </footer>
    </div>
   

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>